# Generated by Django 5.0.3 on 2024-03-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurpose',
            name='role',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], max_length=20),
        ),
    ]
